# pagos-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagos
  template:
    metadata:
      labels:
        app: pagos
    spec:
      containers:
        - name: pagos
          image: trijuank/servicio_camilo:v11  # Reemplazar con la imagen de Docker
          ports:
            - containerPort: 3002
          env:
            - name: POSTGRES_HOST
              value: "pagos-db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: "pagos_db"
            - name: POSTGRES_PORT
              value: "5433"
---
apiVersion: v1
kind: Service
metadata:
  name: pagos-service
spec:
  selector:
    app: pagos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
      nodePort: 31897
  type: NodePort  # Cambiado de ClusterIP a NodePort para exponer el servicio externamente
---
# pagos-db-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagos-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagos-db
  template:
    metadata:
      labels:
        app: pagos-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432  # Puerto interno de PostgreSQL
          env:  # Definir las variables de entorno
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "123456"
            - name: POSTGRES_DB
              value: "pagos_db"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: pagos-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pagos-db
spec:
  selector:
    app: pagos-db
  ports:
    - protocol: TCP
      port: 5433  # Puerto expuesto al clúster
      targetPort: 5432  # Puerto interno del contenedor
      nodePort: 31752  # Asigna un puerto para acceso desde fuera del clúster
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pagos-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
